#---------------------------------------------------------------------

# This file was generated by Image2PyFile.py

from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
#---------------------------------------------------------------------

pacman_png = PyEmbeddedImage( 
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAOtJ"
    "REFUOI2V0zFKRDEQxvHfCnaKoiAoKCKKRxBR0MrWA3gDESuPorWl2GyrrYWCWFjbrGCxpY3a"
    "2DyL95aNIfN2d2DIJJnvn8yQdMR2hAMso49H3LXk/7Nz9FAl/omLUcI1PGfCCm9J/IrNkngW"
    "XwVxt9mfz9b3YCoB3GCmAJ5rxtVsfSOdbBdOTv0nie+xmJ9yNQJQ4R07pdrhoUXYw1kkHPRg"
    "OkrAt2EjQ7seo4RLrESA/TEAAz+NIC8TQJ5wnAO2JgBUOCndYlfdtDbhLw6jMqhf420g7mIh"
    "Te4EkKXmiuuGf+RD/dz7aeIfEd94e2NA3moAAAAASUVORK5CYII="
    )

catalog["pacman.png"] = "pacman_png"
GetData_pacman_png   = pacman_png.GetData
GetImage_pacman_png  = pacman_png.GetImage
GetBitmap_pacman_png = pacman_png.GetBitmap
GetIcon_pacman_png   = pacman_png.GetIcon

#---------------------------------------------------------------------

save_png = PyEmbeddedImage( 
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAANpJ"
    "REFUOI2t06FOA0EQBuCvmyOAoAHTUMUbkD4NnlRgkAiCqus7IPDYOh4FQ4KkGGiaihIOxC1k"
    "c9m9XAK/2fkn8/87O5MdYIIphhhpMJDHF2q84BX3FS6jAdxGccmgxiHOIw9VUvyMi4KwjbN4"
    "bgM+Iql6isdJ/Bl6ior4V4O6p2adkqoVD5U3QLPG45LBGO89u/jFn2fQXt0WT5m6n9aPcgZ7"
    "CX/EaeGyOa7byYBVwrsGuJ9LBlzhJvKDDoOdTG43aN49xx1OOgxyA39LhzjTfKgSFlgmfIOH"
    "b8VvH/0jtL5BAAAAAElFTkSuQmCC"
    )

catalog["save.png"] = "save_png"
GetData_save_png   = save_png.GetData
GetImage_save_png  = save_png.GetImage
GetBitmap_save_png = save_png.GetBitmap
GetIcon_save_png   = save_png.GetIcon

#---------------------------------------------------------------------

cog_png = PyEmbeddedImage( 
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAASZJ"
    "REFUOI2F000rhVEQB/Df9S7Fyk6+CDsLK2sLH0H5ErYslLK7SylKQkpeitjIystCsbASUZRu"
    "hGvxnKvxdC5T05mZ5z//mTlznormMoRhfOASW39gf0klnfOoJ90M3yoR3FJKnsNFsmshXk/n"
    "Cs6aVZ4NFY8SUcO/wXLwN3IEewHwnz6jM0dyUAKuYBq3IVZDdyOhDWMYTS13B7IJLIbx7tGe"
    "CKYwiF2oZlp8yHQ3mcFVW/CVAdczsay0YgD9OEYv+tCDU1wlXAe2FRdXUzyqV+yUCfdDe59Y"
    "wwKuQ/wNXbluljIzNtPzRlJ8iW3BvsNj8J/COBTbyMpqAsNMqLieYieKdf4UjlVhXHFh/J6z"
    "8QONJPtnc2WC96RwqNjQu+KFwku55W9fKmlmswa+iAAAAABJRU5ErkJggg=="
    )

catalog["cog.png"] = "cog_png"
GetData_cog_png   = cog_png.GetData
GetImage_cog_png  = cog_png.GetImage
GetBitmap_cog_png = cog_png.GetBitmap
GetIcon_cog_png   = cog_png.GetIcon

#---------------------------------------------------------------------

play_png = PyEmbeddedImage( 
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAP9J"
    "REFUOI2N0S1LREEUxvHfXsUXEAwGEdyk3WDTsKBFFhQMxsVPYjDYLBa7fgYxatEkFjEvggoi"
    "clUUg0XLXJgddu7uA0858/zPnDPTkFcLSyhwg+uabI8msI9n/AU/hNrYIHgLvxGY+hPbOXi3"
    "Bky9kcKzSeAN3QFN5mEk7HWI5ajhF5rhvJWZeAYv0MFPn10rTeG2zwRP2Cuwgsncw+A7TLeA"
    "u6g+h2aB8Ro4VjfcWqnAaIH7IeCjMHY7qpV4hUVc6N2vDKE2PvT/hUvsVN3Wk8NHnGXAyvE0"
    "4HgAEPsgt+vJEPBpDq60GR4nBd+xloYbmSarodF0yJQ4x1Ua/AfoG3NG/8sbywAAAABJRU5E"
    "rkJggg=="
    )

catalog["play.png"] = "play_png"
GetData_play_png   = play_png.GetData
GetImage_play_png  = play_png.GetImage
GetBitmap_play_png = play_png.GetBitmap
GetIcon_play_png   = play_png.GetIcon

